[build]
  base = "frontend"
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  CI = "false"
  NETLIFY = "true"
  BROWSERSLIST_IGNORE_OLD_DATA = "true"
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 